[package]
name = "lol-discord-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12.2" 
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"